### ISSUE TITLE
Getting error on import - only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by puffstream** [mschez/react-side-bar#1]
Hello,

like react-side-bar component but having issues trying to import into my application.

Getting error on import - only one instance of babel-polyfill is allowed

Any ideas?
James

**Comment by mschez** [comment]
Hi,

yes, I think this is because I added babel-polyfill in the bundle of production. I updated version 0.3.3. Try update your package and tell me about the result.
Thank you for your support.

**Comment by puffstream** [comment]
Okay, I've tried a basic import into my Component, now getting this error:

Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of ...

**Comment by mschez** [comment]
Ok, this is a Warning. I need time to research about this, but now the component is working for you, right?

**Comment by puffstream** [comment]
Yes but outside of the package, I had to copy the code out into its own component. Happy to keep posting the findings but I would try using it with one of the React Starter Kits, see how you get on.

**Comment by mschez** [comment]
Ok, I fixed the problem with the module export in v0.3.5. If you want to try, you have to execute `npm install`. Thank you so much for the support.

**Comment by puffstream** [comment]
Thanks mschez, I will give it a try as soon as I can. Thank you.

**Comment by puffstream** [comment]
Hi @mschez, I've had the opportunity to try the sidebar update, all is working well. Just noticed one warning - warning.js:44 Warning: Failed propType: Invalid prop `children` of type `object` supplied to `t`, expected `array`. Check the render method of `<my component>`. Still works with the warning, but would be good to remove it.

On another note, I have had to implement another state, e.g. offset, so that we can see partial of the side bar when closed, like viewing icons only at a collapsed state. Not sure if you will add something like this into your component or we could extend from the existing code through props? Thank you.

**Comment by puffstream** [comment]
Sorry, also I noticed you added the following line in the close method:

`if (!this.isOpen() && !this.state._opening) return;`

I had to remove this so I could get my offset state working, what was the reasoning to add this line in? Purpose? Thank you.
