### ISSUE TITLE
Breaks removal of browser UI on mobile devices

### ISSUE THREAD

**Issue by JesperWe** [mschez/react-side-bar#10]
On mobile devices the browser UI usually moves out of the way when the page is scrolled down. react-side-bar breaks this functionality. On some screens this results in a very small part of the page being visible:

![image](https://user-images.githubusercontent.com/1643015/30975539-d3d562bc-a472-11e7-8757-997e3e8b252d.png)

**Comment by mschez** [comment]
Sorry for the inactivity period.

I think this issue is not related to this component. https://mschez.github.io/react-side-bar/public/ is just a demo, it is not a real example.
By the way, if the screen is very small... 🤷🏻‍♂️

Thanks for your support.
