### ISSUE TITLE
Sidebar not displaying

### ISSUE THREAD

**Issue by CIS-gvoit** [mschez/react-side-bar#4]
I followed your README instructions but am unable to get the component to render (seemingly at all). I ran ```npm install --save react-side-bar``` which succeeded. I then imported the new module into my existing component with ```import Sidebar from 'react-side-bar';``` as shown below. I've set the backgroundColor of the component to red in the hopes that if it's there, but just not rendering text, etc., I would still be able to see where it is rendering. But even this does not seem to show up. I've created a test Div above it and below it, but can't get your component to render at all. Any suggestions for what I'm doing wrong?

```js
import React, { Component } from 'react';
import Sidebar from 'react-side-bar';
import ReactDOM from 'react-dom';

var TAG = "MainApp | "

export default class App extends Component {

  render(){
    return (
      <div>
        <div style={{backgroundColor: bgColors.Red, height: 100, width: 100}}>Test Div</div>
        <div>
          <Sidebar {... sidebarProps} style={{backgroundColor: bgColors.Red, height: 500, width: 200}}/>
        </div>
        <div id="container">
          {this.props.children}
        </div>
      </div>
    )
  }
}

const sidebarProps = {
    bar: (<div>Amazing Sidebar</div>),
    opened: true,
    onClose: () => {
        setState({ opened: false })
    },
    onOpen: () => {
        setState({ opened: true })
    },
    size: 200
};

const bgColors = { "Default": "#81b71a",
                    "Blue": "#00B1E1",
                    "Cyan": "#37BC9B",
                    "Green": "#8CC152",
                    "Red": "#E9573F",
                    "Yellow": "#F6BB42",
};
```

**Comment by mschez** [comment]
This seems a incorrect implementation. Please, read the docs and try the example. Thanks!
