### ISSUE TITLE
Sidebar right side initial state

### ISSUE THREAD

**Issue by exylzior** [mschez/react-side-bar#5]
I'm trying to set in the initial state for the property side: 'right' but upon initializing it gives an error of 
Uncaught TypeError: Cannot read property 'clientWidth' of undefined in the console. This the initial state that I'm trying to use.

constructor(props) {
    super(props);
	this.displayName = 'SideBarExample';
    this.state = {
      barOpened: false,
      duration: 150,
      fx: 'cubic-bezier(0, 1, 0.85, 1)',
      mode: 'push',
	  side: 'right',
      size: 256,
      tolerance: 70,
      topBarIncluded: false,
      touch: true,
      touchSize: 80
    };

**Comment by mschez** [comment]
Thanks for your feedback, I think it is a bug, I will research it and include it a fix for next versions. Thanks again!

**Comment by exylzior** [comment]
Looking forward for your fix

Thanks

**Comment by aviram83** [comment]
this is still happen when component is initial with side="right"

**Comment by mschez** [comment]
It is solved in v1.0.3. Sorry for the inactivity period.
