### ISSUE TITLE
Responsive sidebar for tablet

### ISSUE THREAD

**Issue by jonathancochran** [mschez/react-side-bar#8]
How would you recommend we keep the sidebar open for tablet and desktop? Media queries or another approach? Cheers!

**Comment by mschez** [comment]
Sorry for the inactivity period.

Media Queries probably is the best approach, in this case, to keep the sidebar open you only need a flag, so you can implement something similar to:

```
<SideBar
  opened: window.matchMedia('(max-width: 1280px)').matches
  ...
/>
```
It will open the SideBar if the width is over 1280 px.

Thanks
