### ISSUE TITLE
Support for older browsers?

### ISSUE THREAD

**Issue by jonathancochran** [mschez/react-side-bar#9]
It seems that there is no vendor prefix for the css transforms, which eliminates support for older browsers. Would be nice to add this in :)

**Comment by mschez** [comment]
Sorry for the inactivity period.

There is a basic prefix method to support older browsers, you can see it here https://github.com/mschez/react-side-bar/blob/master/src/SideBar.js#L60.
Prefixing it is working for `'Moz', 'ms', 'O', 'WebKit'`
